# Generated by Django 4.1.7 on 2023-02-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_employee_bonus_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
    ]
